default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  username: sarad
  password: 
  socket: /var/run/postgresql

development:
  <<: *default
  database: jobspot_development

test:
  <<: *default
  database: jobspot_test

production:
  <<: *default
  database: jobspot_production
